version: "3.9"
services:
  app:
    build: .
    container_name: product-comparison
    ports:
      - "2222:2222"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env   # âœ… loads environment variables
    command: npm run dev